const { createRpcHandler } = require("./rpcHandlerFactory");

module.exports = {
  getUsuario: createRpcHandler("buscar_usuario"),
  listarLiberadores: createRpcHandler("listar_liberadores"),
  listarAmbientes: createRpcHandler("listar_tipos_ambientes"),
  listarVendedores: createRpcHandler("listar_vendedores"),
  listarLojas: createRpcHandler("listar_lojas"),
  listarTipoCliente: createRpcHandler("listar_tipo_cliente"),
  listarEtapas: createRpcHandler("listar_etapas"),
  listarTipoContrato: createRpcHandler("listar_tipo_contrato"),
  fillTableAcessorios: createRpcHandler("get_acessorios"),
  getGroupedAcessorios: createRpcHandler("get_group_by_acessorios"),
  getDate: createRpcHandler("buscar_data"),
  setDate: createRpcHandler("set_data", "body"),
  setEtapa: createRpcHandler("set_etapa", "body"),
  getCodigoBarras: createRpcHandler("get_projeto_codigo_barras"),
  getOperadores: createRpcHandler("get_operadores"),
  setTipo: createRpcHandler("set_tipo"),
  getMontador: createRpcHandler("get_montadores", "none"),
  validateLogin: createRpcHandler("validate_login"),
  getSolicitacoes: createRpcHandler("get_solicitacoes"),
  getPecas: createRpcHandler("total_pecas"),
  getOcorrencia: createRpcHandler("get_ocorrencias"),
  getFalhas: createRpcHandler("get_falhas"),
  getCausa: createRpcHandler("get_causa_falha"),
  getMax: createRpcHandler("max_order"),
  getLojas: createRpcHandler("listar_lojas"),
};
