const router = require('express').Router()
const c = require('../controllers/ultilsController')

router.get('/liberadores',    c.listarLiberadores)
router.get('/ambientes',      c.listarAmbientes)
router.get('/vendedores',     c.listarVendedores)
router.get('/lojas',          c.listarLojas)
router.get('/tipo-cliente',   c.listarTipoCliente)
router.get('/etapas',         c.listarEtapas)
router.get('/tipo-contrato',  c.listarTipoContrato)
router.get('/acessorios',     c.fillTableAcessorios)
router.get('/categorias',     c.listarCategorias)
router.get('/data',           c.getDate)
router.post('/data',          c.setDate)
router.get('/table-data',     c.getTableData)  // get_data(p_id)
router.post('/etapa',         c.setEtapa)
router.post('/tipo',          c.setTipo)
router.get('/codigo-barras',  c.getCodigoBarras)
router.get('/operadores',     c.getOperadores)
router.get('/montadores',     c.getMontador)
router.get('/usuario',        c.getUsuario)
router.get('/solicitacoes',   c.getSolicitacoes)
router.get('/pecas-total',    c.getPecas)
router.get('/ocorrencias',    c.getOcorrencia)
router.get('/falhas',         c.getFalhas)
router.get('/causa-falha',    c.getCausa)
router.get('/max-order',      c.getMax)
router.get('/equip-sat',      c.getEquipSat)

module.exports = router
